-- EXPORTED FROM QUICKDBD: HTTPS://WWW.QUICKDATABASEDIAGRAMS.COM/
-- LINK TO SCHEMA: HTTPS://APP.QUICKDATABASEDIAGRAMS.COM/#/D/EAFM8Z
-- NOTE! IF YOU HAVE USED NON-SQL DATATYPES IN YOUR DESIGN, YOU WILL HAVE TO CHANGE THESE HERE.
DROP TABLE IF EXISTS EV_STATIONS;
DROP TABLE IF EXISTS EV_REGISTRATION;
DROP TABLE IF EXISTS EV_SALES_2019;
DROP TABLE IF EXISTS ZIP_CODE_REFERENCE;
DROP TABLE IF EXISTS CENSUS_2019_INCOME;

CREATE TABLE EV_STATIONS (
    STATION_NAME VARCHAR   NOT NULL,
    STREET_ADDRESS VARCHAR,
    CITY VARCHAR   NOT NULL,
    STATE_CODE VARCHAR   NOT NULL,
    ZIP_CODE VARCHAR   NOT NULL,
    STATUS_CODE VARCHAR   NOT NULL,
    ACCESS_DAYS_TIME VARCHAR,
    EV_LEVEL1_EVSE_NUM INT,
    EV_LEVEL2_EVSE_NUM INT,
    EV_DC_FAST_COUNT INT,
    EV_NETWORK VARCHAR,
    LATITUDE VARCHAR   NOT NULL,
    LONGITUDE VARCHAR   NOT NULL,
    EV_ID INT   NOT NULL,
    OWNER_TYPE_CODE VARCHAR,
    OPEN_DATE DATE,
    ACCESS_CODE VARCHAR   NOT NULL,
    FACILITY_TYPE VARCHAR,
    CHARGING_COST VARCHAR,
    CONSTRAINT PK_EV_STATIONS PRIMARY KEY (
        STATION_NAME,LATITUDE,LONGITUDE,EV_ID
     )
);

CREATE TABLE EV_REGISTRATION (
    DMV_ID INT   NOT NULL,
    DMV_SNAPSHOT_DATE VARCHAR   NOT NULL,
    ZIP_CODE VARCHAR   NOT NULL,
    VIN_PREFIX VARCHAR   NOT NULL,
    REGISTRATION_VALID_DATE DATE   NOT NULL,
	STATE_CODE VARCHAR   NOT NULL,
    EV_MAKE_MODEL VARCHAR   NOT NULL
);


CREATE TABLE EV_SALES_2019 (
    STATE_CODE VARCHAR   NOT NULL,
    STATE_NAME VARCHAR   NOT NULL,
    EV_SALES_COUNT VARCHAR   NOT NULL,
    EV_MARKET_SHARE VARCHAR   NOT NULL,
    CONSTRAINT PK_EV_SALES_2019 PRIMARY KEY (
        STATE_CODE, STATE_NAME
     )
);

CREATE TABLE ZIP_CODE_REFERENCE (
    ZIP_CODE VARCHAR   NOT NULL,
    COUNTY_NAME VARCHAR   NOT NULL,
    STATE_CODE VARCHAR   NOT NULL,
	COUNTY_CODE VARCHAR   NOT NULL
);

CREATE TABLE CENSUS_2019_INCOME (
    ZIP_CODE VARCHAR   NOT NULL,
    TOTAL_HOUSEHOLDS VARCHAR   NOT NULL,	
    TOTAL_HOUSEHOLDS_MARGIN_ERROR VARCHAR   NOT NULL,	
    MEDIAN_HOUSEHOLDS_ESTIMATE_INCOME VARCHAR   NOT NULL,
    MEDIAN_HOUSEHOLDS_MARGIN_ERROR	VARCHAR   NOT NULL,
    MEAN_HOUSEHOLDS_ESTIMATE_INCOME	VARCHAR   NOT NULL,
    MEAN_HOUSEHOLDS_MARGIN_ERROR VARCHAR   NOT NULL
);


ALTER TABLE EV_STATIONS ADD CONSTRAINT FK_EV_STATIONS_STATE_CODE FOREIGN KEY(STATE_CODE)
REFERENCES EV_SALES_2019 (STATE_CODE);

ALTER TABLE EV_STATIONS ADD CONSTRAINT FK_EV_STATIONS_ZIP_CODE FOREIGN KEY(ZIP_CODE)
REFERENCES ZIP_CODE_REFERENCE (ZIP_CODE);

ALTER TABLE EV_REGISTRATION ADD CONSTRAINT FK_EV_REGISTRATION_ZIP_CODE FOREIGN KEY(ZIP_CODE)
REFERENCES ZIP_CODE_REFERENCE (ZIP_CODE);

